import Dashboard from "@components/dashboard/Dashboard ";
import Loading from "./loading";
import { Suspense } from "react";

export const metadata = {
  title: "JollyPlanner",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <Suspense fallback={<Loading />}>
      <main className="font-bodyFont">
        <div>
          <Dashboard />
        </div>
      </main>
    </Suspense>
  );
}
